/**
 * Phone wallpaper definitions for /backgrounds page.
 * Wallpapers are generated by: node scripts/generate-wallpapers.js
 */

export interface Wallpaper {
  id: string;
  title: string;
  source: string;
  category: "logo" | "album";
}

export const wallpapers: Wallpaper[] = [
  // Logo-based
  { id: "logo-black", title: "Logo on Black", source: "/wallpapers/logo-black.webp", category: "logo" },
  { id: "logo-white", title: "Logo on White", source: "/wallpapers/logo-white.webp", category: "logo" },
  // Album art — close-up (fills frame)
  { id: "story-of-an-artist-closeup", title: "Story of an Artist (close-up)", source: "/wallpapers/story-of-an-artist-closeup.webp", category: "album" },
  { id: "sandpiper-closeup", title: "Sandpiper (close-up)", source: "/wallpapers/sandpiper-closeup.webp", category: "album" },
  { id: "the-sky-is-falling-closeup", title: "The Sky Is Falling (close-up)", source: "/wallpapers/the-sky-is-falling-closeup.webp", category: "album" },
  { id: "walking-the-cow-closeup", title: "Walking The Cow (close-up)", source: "/wallpapers/walking-the-cow-closeup.webp", category: "album" },
  { id: "mozworth-debut-closeup", title: "mozworth debut (close-up)", source: "/wallpapers/mozworth-debut-closeup.webp", category: "album" },
  { id: "goodbye-colorado-closeup", title: "Goodbye Colorado (close-up)", source: "/wallpapers/goodbye-colorado-closeup.webp", category: "album" },
  { id: "postcard-closeup", title: "Postcard (close-up)", source: "/wallpapers/postcard-closeup.webp", category: "album" },
];
